all:
	g++  -o a Test.cpp -g -I ./ -I ../FileStorage/
	#g++  -o a1 Test.cpp -O2 -I ./ -I ../FileStorage/
	#g++ -o Test1 -O2 Main.cpp -I ./ -I ../FileStorage/
	g++ -o Test -O2 Main.cpp -I ./ -I ../FileStorage/
